// data types

"use strict";// treat all JS code as newer version;

//alert("hello") // we are using nodejs , not browser

console.log(3 + 3);
console.log("mohit");

let name = "mohit"; // string
let age = 18; // number
let isLoggedIn = false; // boolean
let state = null ; // standlone value

console.log(typeof undefined);  // output is undefined
console.log(typeof null); // output is object



